# Reference from: https://github.com/benmoose39/YouTube_to_m3u/blob/main/.github/workflows/m3u_Generator.yml

name: Playlist Generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Main
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: git add
        run: |
          git add -A
          ls -la

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated playlist.m3u
