name: Playlist Generator

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Main
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Changes detected"
          echo "::set-output name=changes::$(git status --porcelain)"

      - name: Commit & push
        if: steps.check_changes.outputs.changes != ''
        run: |
          git commit -m "Updated playlist.m3u"
          git push
